CREATE TABLE IF NOT EXISTS detection_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    task_name VARCHAR(255) COMMENT '任务名称',
    task_type VARCHAR(50) COMMENT '任务类型(IMAGE/VIDEO)',
    model_name VARCHAR(255) COMMENT '模型名称',
    model_path VARCHAR(500) COMMENT '模型路径',
    input_path VARCHAR(500) COMMENT '输入文件路径',
    output_path VARCHAR(500) COMMENT '输出文件路径',
    status VARCHAR(20) COMMENT '状态(SUCCESS/FAILED)',
    total_detections INT DEFAULT 0 COMMENT '检测目标总数',
    class_distribution TEXT COMMENT '类别分布(JSON)',
    avg_confidence DECIMAL(5,3) COMMENT '平均置信度',
    min_confidence DECIMAL(5,3) COMMENT '最小置信度',
    max_confidence DECIMAL(5,3) COMMENT '最大置信度',
    detection_result TEXT COMMENT '检测结果(JSON)',
    conf_threshold DECIMAL(5,3) COMMENT '置信度阈值',
    iou_threshold DECIMAL(5,3) COMMENT 'IoU阈值',
    process_time BIGINT COMMENT '处理时间(ms)',
    error_message TEXT COMMENT '错误信息',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted TINYINT DEFAULT 0 COMMENT '删除标记(0-未删除,1-已删除)',
    version INT DEFAULT 1 COMMENT '版本号'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测历史表';