CREATE TABLE IF NOT EXISTS detection_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    task_name VARCHAR(255) COMMENT '任务名称',
    task_type VARCHAR(50) COMMENT '任务类型(IMAGE/VIDEO)',
    model_name VARCHAR(255) COMMENT '模型名称',
    model_path VARCHAR(500) COMMENT '模型路径',
    input_path VARCHAR(500) COMMENT '输入文件路径',
    output_path VARCHAR(500) COMMENT '输出文件路径',
    status VARCHAR(20) COMMENT '状态(SUCCESS/FAILED)',
    total_detections INT DEFAULT 0 COMMENT '检测目标总数',
    class_distribution TEXT COMMENT '类别分布(JSON)',
    avg_confidence DECIMAL(5,3) COMMENT '平均置信度',
    min_confidence DECIMAL(5,3) COMMENT '最小置信度',
    max_confidence DECIMAL(5,3) COMMENT '最大置信度',
    detection_result TEXT COMMENT '检测结果(JSON)',
    conf_threshold DECIMAL(5,3) COMMENT '置信度阈值',
    iou_threshold DECIMAL(5,3) COMMENT 'IoU阈值',
    process_time BIGINT COMMENT '处理时间(ms)',
    error_message TEXT COMMENT '错误信息',
    create_time     bigint            null comment '创建时间（毫秒时间戳）',
    update_time     bigint            null comment '更新时间（毫秒时间戳）',
    deleted         tinyint default 0 not null comment '逻辑删除（0-未删，1-已删）',
    version         bigint  default 1 not null comment '版本号（用于乐观锁）'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='检测历史表';